config/routes.rb
Rails.application.routes.draw do



  get 'sessions/new'

  root 'static_pages#home'

 # get 'static_pages/home', to: 'static_pages#home'

  get '/help', to: 'static_pages#help'


  get '/about', to: 'static_pages#about'
 

  get '/contact', to: 'static_pages#contact'


  get '/signup', to: 'users#new'
  #get 'signup' => 'users#new'

  post '/signup', to: 'users#create'
  #post 'signup' => 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
   attr_accessor :remember_token
   
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX },uniqueness: {case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 10 }

    #Returns the hash digest of the given string.
    def self.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)  
    end        
    
    #Returns a random token
    def self.new_token
        SecureRandom.urlsafe_base64
    end
    
    #Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    #Returns true if the given token matches the digest
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

#forgets a user
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  #def hello
   # render html: "hello, world!"
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      redirect_to @user
    else
      flash.now[:danger] = 'Invalid email/password combination'
    render 'new'
  end
end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])

  end

  def new
    @user = User.new
  end

    def create
      @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:success] = "Welcome to the Sample App"
        redirect_to @user
      else
        render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
          base_title
        else
          page_title + "|" + base_title
        end
      end
    end

app/helpers/sessions_helper.rb
module SessionsHelper
    #logs in the given user
    def log_in(user)
        session[:user_id] = user.id
    end

    #Remembers a user in a persistent session
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    #Returns the user corresponding to the remember token cookie
    def current_user
        if(user_id = session[:user_id])
            @current_user ||=User.find_by(id: user_id)
        elsif(user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
               log_in user
               @current_user = user
            end
        end
    end 

    #def current_user
     #   @current_user ||= User.find_by(id: session[:user_id])
    #end
    
    #Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end

     #forgets a persistent session
     def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    #logs out the current user
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
          base_title
        else
          page_title + "|" + base_title
        end
      end
end

app/helpers/users_helper.rb
module UsersHelper

    def gravatar_for(user, size: 80 )
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   'about_path' %></li>
      <li><%= link_to "Contact", 'contact_path' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", 'root_path', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Users", '#' %></li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
        <ul class="dropdown-menu">
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", '#' %></li>
        <li class="divider"></li>
        <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <ul>
        <li>
        <% else %>
        <li><%= link_to "Log in", login_path %>
        <% end %>
      
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>  
    
     <%= render 'layouts/shim' %>
  </head>
  <body> 

  <%= render 'layouts/header' %>

    <div class="container">
    <% flash.each do |message_type, message| %>
   <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <!--<div class="alert alert-<%= message_type %>"><%= message %></div> -->
    <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
This form contains <%= pluralize(@user.errors.count, "error") %>.
</div>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>
<p>
  This is the home page for the
  <a href="http://www.railstutorial.org/">About|Ruby on Rails Tutorial Sample App</a>
  sample application.
</p>
<div class="container">
  <div class="grid-services">Services</div>
  <div class="grid-org">Organizations</div>
  <div class="grid content">Main Content</div>
  <div class="grid extra">Extra Content</div>
  <div class="grid connections">Connections</div>


<container {
  	display: grid;
  	grid-template-columns: 1fr 3fr;
        grid-column-gap: 10px;
        grid-row-gap: 15px;
}

.grid-services {
  background-color: #444;
  color: #fff;
  padding: 25px;
  font-size: 3rem;
} 

.Services {
  grid-column-start: 1;
  grid-column-end: 3;
  grid-row-start: 1;
  grid-row-end: 2;
}
.Organizations {
  grid-column-start: 1;
  grid-column-end: 2;
  grid-row-start: 2;
  grid-row-end: 4;
  background: #a0c263;
}
%>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
  
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

<form>
    <label for="firstName" class="first-name">First Name</label>
    <input id="firstName" type="text">
 
    <label for="lastName" class="last-name">Last Name</label>
    <input id="lastName" type="text">

    <label for="phoneNumber" class="phone-number">Phone Number</label>
    <input id="phoneNumber" type="text">

    <label for="homeAdress" class="home-adress">Home Adress</label>
    <input id="homeAdress" type="text">
 
    <!-- more inputs -->
</form>



<form {
  display: grid;
  grid-template-columns; 1fr 1fr

    overflow: hidden;
}

form{
  display: grid;
  grid-template-columns:1fr 2fr
}
 
label {
  display:grid;
  grid-template-columns: 1fr 2fr
    float: left;
    width: 200px;
    padding-right: 24px;
}
 
input {
    float: left;
    width: calc(100% - 200px);
}
 
button {
    float: right;
    width: calc(100% - 200px);
}%>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>


<h1>Help</h1>
<p>
  This is the home page for the
</p>  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.

<html>
<head>
<title>CSS Grids</title>
<style>

.wrapper{
  display:grid;
  grid-template-columns:70% 30%;
  grid-column-gap:1em;
  grid-row-gap:1em;
}
.wrapper > div{
  background:#eee;
  padding:1em;
}
</style>
</head>
<body>
<div class="wrapper">
<div>
This is the help page for the sample_app. If you need help, just go ahead and ask coz it wont be such a problem.
</div>

<div>
And also you can contact our rsecue centers. I know this is crazy but just get used to it.
</div>

 <div>
 Dont get scared when you cant do anything.Just rise up above your fears and solve the errors like am planning to do.
 Ive had enough of errors though.
 </div>

</div>
</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
        <title>Sample App Solutions</title>
          <div class="center jumbotron">
              <h1>Welcome to the Sample App</h1>

       <h2>
      This is the home page for the
      <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
      </h2>


    <%= link_to "Sign up now!",signup_path, class: "btn btn-lg btn-primary" %>
</div>

   <%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>
   <%= image_tag("kitten.jpg")%>
  

    <header id="showcase" class="grid">
    <div class=bg-image></div> 
  <a href="#section-b" class="btn">Read More</a>
    </header>


<!--main area-->
    <main id="main">

    <!-- section-a-->
    <section id="section-a" class="grid">
    <div class="content-wrap">
    <p>This sample app issues web development programs. If you want front end or backend. It's all here.I want this to be simple.</p>
    </div>
</section>

<!--section-b-->
<section id="section-b" class="grid">
  <ul>
    <li>
      <div class="card">
<p>Talk about your first web development experience.Mine was terrible, I must say, but i came to get used to it.</p>
<img src="https://bit.ly/fcc-relaxing-cat" alt="">
      <div class="card-content">
<h3 class="card-title">Web Development</h3>
<p>Get used to these things coz time is running out and we are running out of time. This day is quite terrible.</p>

     </div>
    </div>
</li>

<li>
   <div class="card">
<img src="https://www.pexels.com/photo/light-nature-sun-sunrise-87215/" alt="">
  <div class="card-content">
<h3 class="card-title">Graphic design</h3>
<p>Get used to these things coz time is running out and we are running out of time. This day is quite terrible.</p>

   </div>
   </div>
</li>
</ul>
  </section>

  <!--section-c-->

<section id="section-c" class="grid">
<div class="card-content">
<h3 class="card-title">We handle your digital needs</h3>
<p>Save yourself the energy by being normal like us</p>
</div>
</section>

<section id="sectiion-d" class="grid">
<div class="box">
<h3 class="card-title">Contact us</h3>
<p>contact us on facebook, tweeter</p>
</div>
<div class="box">
<h3 class="card-title">About us</h3>
<p>We love you</p>
</div>
</section>

 </main>
 

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
<h1>Sign up</h1>
  <div class="col-md-6 col-md-offset-3">
<%= form_for(@user, url: signup_path) do |f| %>
<%= render 'shared/error_messages' %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :email%>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :password%>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

<%= f.submit "Create my account", class: "btn btn-primary"%>
<% end %>
</div>
</div> 

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
<aside class="col-md-4">
<section class="user_info">

<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>
</section>
</aside>
</div>